[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wordmill"
version = "0.0.1"
description = "A document summary tool"
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://example.com"
